// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PackageFoodManagementSystem.Repository.Data;

#nullable disable

namespace PackageFoodManagementSystem.Repository.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260120161505_MakeAddressOptional")]
    partial class MakeAddressOptional
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PackageFoodManagementSystem.Repository.Models.Batch", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                // FIXED: Restored the missing property name "BatchNumber"
                b.Property<string>("BatchNumber")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("ExpiryDate")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.ToTable("Batches");
            });

            // ... [Bill and Customer entities are correct]

            modelBuilder.Entity("PackageFoodManagementSystem.Repository.Models.OrderItem", b =>
            {
                b.Property<int>("OrderItemID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemID"));

                b.Property<int>("BatchID")
                    .HasColumnType("int");

                b.Property<DateTime>("ExpiryDate")
                    .HasColumnType("datetime2");

                b.Property<int>("OrderID") // Using uppercase ID to match relationship
                    .HasColumnType("int");

                // REMOVED: Duplicate "OrderId" property that was causing conflicts

                b.Property<int>("ProductId")
                    .HasColumnType("int");

                b.Property<int>("Quantity")
                    .HasColumnType("int");

                b.Property<decimal>("Subtotal")
                    .HasColumnType("decimal(18,2)");

                b.Property<decimal>("UnitPrice")
                    .HasColumnType("decimal(18,2)");

                b.HasKey("OrderItemID");

                b.HasIndex("OrderID");

                b.ToTable("OrderItems");
            });

            // ... [Remaining relationship configurations are intact]
#pragma warning restore 612, 618
        }
    }
}