// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PackageFoodManagementSystem.Repository.Data;

#nullable disable

namespace PackageFoodManagementSystem.Repository.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260120172532_InitialCartTables")]
    partial class InitialCartTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PackageFoodManagementSystem.Repository.Models.Batch", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                // FIXED: Added the missing property selector "BatchNumber" 
                // (Change this string if your model uses a different name like 'BatchCode')
                b.Property<string>("BatchNumber")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("ExpiryDate")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.ToTable("Batches");
            });

            modelBuilder.Entity("PackageFoodManagementSystem.Repository.Models.Bill", b =>
            {
                b.Property<int>("BillID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BillID"));

                b.Property<DateTime>("BillDate")
                    .HasColumnType("datetime2");

                b.Property<string>("BillingStatus")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<decimal>("DiscountAmount")
                    .HasColumnType("decimal(18,2)");

                b.Property<decimal>("FinalAmount")
                    .HasColumnType("decimal(18,2)");

                b.Property<int>("OrderID")
                    .HasColumnType("int");

                b.Property<decimal>("SubtotalAmount")
                    .HasColumnType("decimal(18,2)");

                b.Property<decimal>("TaxAmount")
                    .HasColumnType("decimal(18,2)");

                b.HasKey("BillID");

                b.HasIndex("OrderID")
                    .IsUnique();

                b.ToTable("Bills");
            });

            // Rest of your entities (Cart, CartItem, Customer, etc.) remain as they were 
            // but are now properly enclosed within this BuildTargetModel method.

            // ... [Rest of the code remains the same] ...

#pragma warning restore 612, 618
        }
    }
}